# FlagGems backends Configuration
# This file defines environment settings for weekly testing
name: PPU-ZW810E
vendor: THead

# Runner labels for this backends (self-hosted)
runner_labels: 810e-flaggems-weekly

# Container image for this backends
container_image: baai-cp-registry.cn-wulanchabu.cr.aliyuncs.com/flagos/flagos:vllm-qwen3-next-0528

# GPUs to test for this backends
test_gpus: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

# Output base directory for this backends
output_base_dir: /home/flaggems/weekly
